---
kind: pipeline
name: New version
type: docker

steps:
  - name: build
    image: node:12
    commands:
      - yarn install
      - yarn lint
      - yarn test -u
      - yarn build

  - name: publish
    image: plugins/npm
    settings:
      token:
        from_secret: npm_token
      email:
        from_secret: npm_email
    when:
      branch:
        - master

  - name: pulish-storybook
    image: node:12
    environment:
      TOKEN:
        from_secret: chromatic_token
    commands:
      - yarn add --dev chromatic
      - npx chromatic --project-token $TOKEN
    when:
      branch:
        - feature/build-storybook

trigger:
  event:
    - push
