---
kind: pipeline
name: New version
type: docker

steps:
  - name: build
    image: node:12
    commands:
      - yarn install
      - yarn lint
      - yarn test
      - yarn build

  - name: publish
    image: plugins/npm
    settings:
      token:
        from_secret: npm_token
      email:
        from_secret: npm_email
    when:
      branch:
        - master

trigger:
  event:
    - push
